language: ruby

rvm:
  - 2.5.

gemfile:
  - Gemfile

git:
  submodules: .gitmodules

before_install:
  - git submodule update --init --recursive

install: 
  - bundle install

script:
  - bundle exec rspec spec