language: ruby
ruby:
  - 2.5
# rvm:
#  - 1.29
before_install:
  - gem update --system
  - gem install bundler
# install: gem install rails
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: 11

# before_install: 
#   - bundle install

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec