# language: ruby
# # script: gulp
# rvm:
#   - 2.5.0

# # env:
# #   - DB=postgresql
# # script:
# #   - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
# #   - bundle exec rspec test/
# before_script:
#   - cp config/database.travis.yml config/database.yml
#   #- mysql -e 'create database mydb_test'
# # bundler_args: --binstubs=./bundler_stubs

# git:
#   submodules: false

# # - 1.9.3
# # - jruby-19mode
# # - rbx-2
# # language: ruby
# # ruby:
# #   - 2.5.0
# # rvm:
# #  - 1.29

# before_install:
#   - gem update --system
#   - gem install bundler
#   - bunlde install
# install: 
#   - gem install rails
# # before_script:
# #   - cp config/database.yml.travis config/database.yml
# #   - psql -c 'create database travis_ci_test;' -U postgres

# addons:
#   postgresql: 11

# # before_install: 
# #   - bundle install

# # script:
# #   - bundle exec rails db:migrate RAILS_ENV=test
# #   - bundle exec rake spec
# #   - bundle exec rspec

# script:
#  — bundle install — jobs=3 — retry=3
#  — bundle exec rake db:create
#  — bundle exec rake db:migrate
#  — bundle exec rspec
# å
# branches:
#   only: 
#     - master


language: ruby
sudo: false
rvm:
    - 2.2.2
env:
    matrix:
        - DB=postgresql
branches:
    only:
        - master
script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    # - bundle exec rake db:test:prepare
    - bundle exec rspec spec/
before_script:
    - cp config/database.travis.yml config/database.yml
    # - cp config/secrets.example.yml config/secrets.yml
    # - mysql -e 'create database trado_test_db'      
    - psql -c 'create database trado_test_db' -U postgres
    # - export DISPLAY=:99.0
    # - sh -e /etc/init.d/xvfb start
    # - npm install bower -g
    # - bower install