language: ruby

rvm:
  - 2.5.0

# gemfile:
#   - Gemfile

git:
  submodules: false

services:
  - postgresql: "11"

before_install:
#   - git submodule update --init --recursive
- psql -c 'create database travis_ci_test;' -U postgres

install: 
  - bundle install

script:
  - bundle exec rspec spec