language: ruby
rvm:
- 2.5.0
# - 1.9.3
- jruby-19mode
- rbx-2
# language: ruby
# ruby:
#   - 2.5.0
# rvm:
#  - 1.29
before_install:
  - gem update --system
  - gem install bundler
# install: gem install rails
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: 11

# before_install: 
#   - bundle install

# script:
#   - bundle exec rails db:migrate RAILS_ENV=test
#   - bundle exec rake spec
#   - bundle exec rspec

  script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

branches:
  only: 
    - master