language: ruby

rvm:
  - 2.5

# gemfile:
#   - Gemfile

git:
  submodules: false

services:
  # - postgresql: "11"
  - postgresql

addons:
  postgresql: "11.3"

before_install:
  # - bundle install
  - gem update --system
  - gem install bundler

before_script:
   - psql -c 'create database eunjeongyi;' -U postgres
   # psql -c 'create database travis_ci_test;' -U postgres
   #cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec