export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"

// export const RESET_FORM = "RESET_FORM"

//Users Attributes
export const REQUEST_NOTEBOOKS= "RREQUEST_NOTEBOOKS"
export const ADD_NOTEBOOK = "ADD_NOTEBOOK"
export const UPDATE_NOTEBOOK = "UPDATE_NOTEBOOK"
export const DELETE_NOTEBOOK = "DELETE_NOTEBOOK"

export const REQUEST_NOTES= "REQUEST_NOTES"
export const ADD_NOTE = "ADD_NOTE"
export const UPDATE_NOTE = "UPDATE_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"

